Project/PrizeDraw/Controllers/DisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrizeDraw.DataLayer;
using PrizeDraw.DataLayer.DataAccess;
using PrizeDraw.DataLayer.Model;
using PrizeDraw.Models;

namespace PrizeDraw.Controllers
{
    public class DisplayController : Controller
    {
        private PrizeDataAccessor _prizeDataAccessor;

        public DisplayController(PrizeDrawDatabaseContext context)
        {
            _prizeDataAccessor = new PrizeDataAccessor(context);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        //GET: Display
        //@see Views/Display/index.cstml
        public IActionResult Index()
        {
            return View(DisplayIndexViewModel.From(_prizeDataAccessor.Get()));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        //GET: Display
        //Display the information about the prize 
        //@see View/Display/Details/#
        public IActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                throw new ArgumentNullException(nameof(id));
            }

            IActionResult result = BadRequest();
            Prize prize = null;
        
            try
            {
                prize = _prizeDataAccessor.Get(id.Value);
            }
            catch
            {
                // Failing to retreive a prize should just redirect back to the prize list.
                result = RedirectToAction("Index");
            }

            if (prize != null)
            {
                DisplayWinningTicketsViewModel displayWinningTicketsModel = new DisplayWinningTicketsViewModel
                {
                    PrizeImage = prize.Image,
                    NextPrizeId = _prizeDataAccessor.GetNextPrize(id.Value)?.Id,
                    PrizeName = prize.Name,
                    PrizeId = prize.Id,
                    NumberOfPrizes = prize.NumberAvailable,
                    SponsorLogo = prize.Sponsor?.Logo,
                    SponsorName = prize.Sponsor?.Name,
                    NumberOfBallots = _prizeDataAccessor.GetNumberOfEligibleBallots(id.Value),
                    PrizesAvailable = _prizeDataAccessor.GetNumberPrizesAvailbleToDraw(id.Value),
                    TotalNumberOfUnwonPrizes = _prizeDataAccessor.GetTotalNumberOfAvailablePrizes(),
                    Winners = _prizeDataAccessor.GetPrizeWinners(id.Value)
                };

                result = View(displayWinningTicketsModel);
            }

            return result;
        }
    }
}

Project/PrizeDraw/Controllers/PrizeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using PrizeDraw.DataLayer;
using PrizeDraw.DataLayer.Model;
using PrizeDraw.DataLayer.DataAccess;
using PrizeDraw.Models;

namespace PrizeDraw.Controllers
{
    public class PrizeController : Controller
    {
        private readonly PrizeDataAccessor _prizeDataAccessor;
        private readonly VendorDataAccessor _vendorDataAccessor;
        private readonly AttendeeDataAccessor _attendeeDataAccessor;

        public PrizeController(PrizeDrawDatabaseContext context)
        {
            _prizeDataAccessor = new PrizeDataAccessor(context);
            _vendorDataAccessor = new VendorDataAccessor(context);
            _attendeeDataAccessor = new AttendeeDataAccessor(context);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        //GET:
        public IActionResult Index()
        {
            return View(PrizeIndexViewModel.From(_prizeDataAccessor.Get()));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        //GET:
        public IActionResult Edit(int id)
        {
            PrizeCreateEditViewModel viewModel = new PrizeCreateEditViewModel(_prizeDataAccessor.Get(id),
               _vendorDataAccessor.Get());

            return View("CreateEdit", viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Edit([FromRoute] int? id, PrizeCreateEditViewModel prizeModel)
        {
            IActionResult result;

            if (ModelState.IsValid && id.HasValue)
            {
                Prize prize = prizeModel.ToPrize();

                _prizeDataAccessor.Update(id.Value, prize);

                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("Create");
            }

            return result;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Details(int id)
        {
            return View(_prizeDataAccessor.Get(id));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            PrizeCreateEditViewModel viewModel = new PrizeCreateEditViewModel(_vendorDataAccessor.Get());

            return View("CreateEdit", viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(PrizeCreateEditViewModel model)
        {
            IActionResult result;

            if (ModelState.IsValid)
            {
                Prize prize = model.ToPrize();

                _prizeDataAccessor.Insert(prize);

                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("Create");
            }

            return result;
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult GenerateWinners()
        {
            int numberOfWinners = _prizeDataAccessor.DrawPrizeWinners().Count();

            PrizeIndexViewModel viewModel = PrizeIndexViewModel.From(_prizeDataAccessor.Get());
            viewModel.NumberOfWinnersDrawn = numberOfWinners;

            return View("Index", viewModel);
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult DrawPrizeWinner([FromBody] GenericPostObject postObject)
        {
            IActionResult result = BadRequest();

            if (postObject != null && postObject.Id.HasValue)
            {
                PrizeWinnerModel winnerModel = DrawWinner(postObject.Id.Value);

                if (winnerModel != null)
                {
                    result = Ok(winnerModel);
                }
                else
                {
                    result = NoContent();
                }
            }

            return result;
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult RedrawWinner([FromBody] RedrawWinnerPostModel model)
        {
            IActionResult result = BadRequest();

            if (model != null && model.PrizeId.HasValue && model.AttendeeId.HasValue)
            {
                _prizeDataAccessor.RemovePrizeWinner(model.PrizeId.Value, model.AttendeeId.Value);

                PrizeWinnerModel winnerModel = DrawWinner(model.PrizeId.Value);

                if (winnerModel != null)
                {
                    result = Ok(winnerModel);
                }
                else
                {
                    result = NoContent();
                }
            }

            return result;
        }

        private PrizeWinnerModel DrawWinner(int prizeId)
        {
            PrizeTicket winningTicket = null;
            Attendee winningAttendee = null;

            // Check to see if there are any prizes that are not won
            if (_prizeDataAccessor.GetNumberPrizesAvailbleToDraw(prizeId) > 0)
            {
                // Draw a prize winner
                winningTicket = _prizeDataAccessor.DrawPrizeWinner(prizeId);
                winningAttendee = _attendeeDataAccessor.Get(winningTicket.AttendeeId);
            }

            PrizeWinnerModel winnerModel = null;
            if (winningTicket != null)
            {
                winnerModel = new PrizeWinnerModel
                {
                    Name = winningAttendee.FirstName + " " + winningAttendee.LastName,
                    OrganizationName = winningAttendee.Company,
                    AttendeeId = winningAttendee.Id
                };
            }

            return winnerModel;
        }
    }
}

Project/PrizeDraw/Views/Display/Details.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DisplayLayout.cshtml";
}
@using PrizeDraw.DataLayer.Model
@model DisplayWinningTicketsViewModel
<div class="row">
    <div class="col-lg-12">
        @if (Model.NextPrizeId.HasValue)
        {
            <a class="btn btn-primary float-right" asp-controller="Display" asp-action="Details" asp-route-id="@(Model.NextPrizeId)">Next Prize</a>
        }
        else
        {
            <a class="btn btn-primary float-right" asp-controller="Display" asp-action="Index">Done</a>
        }
            <span class="h3 text-secondary float-right" id="prizesLeftToDrawText">@((Model.TotalNumberOfUnwonPrizes < 1) ? Model.TotalNumberOfUnwonPrizes : Model.TotalNumberOfUnwonPrizes - 1) Prizes Left to Draw</span>
    </div>
</div>
<div class="row">
     <div class="col-lg-5">
        <p class="display-4" id="prizeName">@Model.PrizeName</p>
        <p class="h2 text-secondary"><span id="numberOfPrizes">@Model.PrizesAvailable</span> Available</p>
        @if (Model.PrizeImage != null)
        {
            <img class="displayPrizeImage" height="100" width="100" src="data:image;base64,@System.Convert.ToBase64String(Model.PrizeImage)" />
        }
        @if (!string.IsNullOrWhiteSpace(Model.SponsorName))
        {
            <p class="h3">Sponsored By: @Model.SponsorName</p>
            @if (Model.SponsorLogo != null)
            {
                <img class="displayPrizeImage" height="300" width="300" src="data:image;base64,@System.Convert.ToBase64String(Model.SponsorLogo)" />
            }
        }
    </div>
     <div class="col-lg-7" id="rightSide">
         @if (Model.NumberOfBallots > 0)
         {
             <span class="display-4">Winners </span>
             <hr />
             <div class="winnerName" id="winnerSpinner">
                 <div class="lds-ring"><div></div><div></div><div></div><div></div></div>
             </div>
             <ul class="inline" id="winnerList">
                 @foreach (Attendee winner in Model.Winners)
                 {
                     <li class="winnerName">
                         <span class="h1">@winner.FirstName @winner.LastName</span>
                         <a class='btn' href='#' onclick='redrawPrizeWinner(this, @winner.Id)'> X</a>
                         <br />
                         <span class='h3'>@winner.Company</span>
                     </li>
                 }
             </ul>
         }
         else
         {
             <p class='text-danger'>Not Enough Ballots For Prize</p>
         }
     </div>
</div>
@section scripts {
    <script>
        var numberOfAvailablePrizes = @Model.PrizesAvailable;
        var allowRedraw = true;

        $(document).ready(function () {
            showHideSpinner(true);
        });

        document.addEventListener("keyup", function (event) {
            if (event.keyCode === 13) {
                event.preventDefault();

                drawWinner();
            }
        });

        function showHideSpinner(hidden) {
            if (hidden) {
                $('#winnerSpinner').hide();
            } else {
                $('#winnerSpinner').show();
            }
        }


        function drawWinner() {
            if (numberOfAvailablePrizes > 0) {
                numberOfAvailablePrizes--;

                showHideSpinner(false);

                $.ajax({
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json',
                    data: JSON.stringify({
                        Id: @Model.PrizeId
                }),
                    url: "@Url.Action("DrawPrizeWinner", "Prize")",
                    success: drawWinnerSuccess,
                    error: function (xhr) {
                        console.log(xhr);

                        showHideSpinner(true);
                    }
                });
            }
        }

        function updateNumberOfPrizesDisplay() {
            $('#numberOfPrizes').html(numberOfAvailablePrizes);
        }

        function showWinner(winnerObj) {
            $('#winnerList').prepend("<li class='winnerName'><span class='h1'>" + winnerObj.name + "</span>" +
                "<a class='btn' href='#' onclick='redrawPrizeWinner(this," + winnerObj.attendeeId + ")'> X</a><br /><span class='h4'>" +
                winnerObj.organizationName + "</span></li>").fadeIn();
        }

        function redrawPrizeWinner(listElement, attendeeId) {
            // Gaurd to prevent double tapping button
            if (allowRedraw) {
                allowRedraw = false;

                showHideSpinner(false);

                $(listElement).closest('.winnerName').hide();

                $.ajax({
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json',
                    data: JSON.stringify({
                        PrizeId: @Model.PrizeId,
                        AttendeeId: attendeeId
                    }),
                    url: "@Url.Action("RedrawWinner", "Prize")",
                    success: drawWinnerSuccess,
                    error: function (xhr) {
                        alert("Well this isn't good...Error drawing winners");
                        console.log(xhr);
                    }
                });
            }
        }

        function drawWinnerSuccess(winnerObj, statusText, xhr) {
            allowRedraw = true;

            showHideSpinner(true);

            if (xhr.status == 200) {
                console.log(winnerObj);

                updateNumberOfPrizesDisplay();
                showWinner(winnerObj);
            } else {
                console.log("Came back from ballot box empty handed...Anyone available to win?");
            }
        }
    </script>
}

Project/PrizeDraw/Views/Display/Index.cshtml
@using PrizeDraw.DataLayer.Model
@model DisplayIndexViewModel

<table class="table">
    <thead>
        <tr>
            <th>Image</th>
            <th>Name</th>
            <th>Sponsor</th>
            <th>Available</th>
            <th>Winners</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (PrizeModel prize in Model.Prizes.OrderBy(p => p.Value).ThenBy(p => p.Name))
    {
        <tr>
            <td>
                @if (prize.Image != null)
                {
                    <img src="data:image;base64,@System.Convert.ToBase64String(prize.Image)" width="100" height="100" />
                }
            </td>
            <td>@prize.Name</td>
            <td>
                @if (string.IsNullOrWhiteSpace(prize.SponsorName))
                {
                    @prize.SponsorName;
                }
                else
                {
                    <span>N/A</span>
                }
            </td>
            <td>@prize.NumberAvailable</td>
            <td>@prize.NumberOfWinners</td>
            <td><a asp-controller="Display" asp-action="Details" asp-route-id="@prize.Id">Draw Prize</a></td>
        </tr>
    }
    </tbody>
</table>