Project/PrizeDraw/Models/Attendee/AttendeeIndexViewModel.cs
using PrizeDraw.DataLayer.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrizeDraw.Models
{
    public class AttendeeIndexViewModel
    {
        public IList<Attendee> Attendees { get; set; }

        public int? NumberImportedAttendees { get; set; }
    }
}

Project/PrizeDraw/Controllers/AttendeeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PrizeDraw.DataLayer;
using PrizeDraw.DataLayer.DataAccess;
using PrizeDraw.DataLayer.Model;
using PrizeDraw.Models;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Spire.Doc;

namespace PrizeDraw.Controllers
{
    public class AttendeeController : Controller
    {
        private AttendeeDataAccessor _attendeeAccessor;

        public AttendeeController(PrizeDrawDatabaseContext context)
        {
            _attendeeAccessor = new AttendeeDataAccessor(context);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        // GET: Attendee
        public IActionResult Index()
        {
            return View(new AttendeeIndexViewModel()
            {
                Attendees = _attendeeAccessor.Get()
            });
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        // GET: Attendee/Details/5
        public IActionResult Details(int id)
        {
            return View(_attendeeAccessor.Get(id));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        // GET: Attendee/Create
        public IActionResult Create()
        {
            return View("CreateEdit", new Attendee());
        }

        // POST: Attendee/Create
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Attendee attendee)
        {
            IActionResult result;

            if (ModelState.IsValid)
            {
                _attendeeAccessor.Insert(attendee);

                result = RedirectToAction(nameof(Index));
            }
            else
            {
                result = RedirectToAction("CreateEdit");
            }

            return result;
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        // GET: Attendee/Edit/5
        public IActionResult Edit(int id)
        {
            return View("CreateEdit", _attendeeAccessor.Get(id));
        }

        // POST: Attendee/Edit/5
        [HttpPost]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Attendee attendee)
        {
            IActionResult result;

            if (ModelState.IsValid)
            {
                attendee.Id = id;
                _attendeeAccessor.Update(attendee);

                result = RedirectToAction("Index");
            }
            else
            {
                result = RedirectToAction("CreateEdit");
            }

            return result;
        }
        /// <summary>
        /// Import Button Event handler
        /// </summary>
        /// <param name="attendeeFile">csv file</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles="Admin")]
        public IActionResult Import(IFormFile attendeeFile)
        {
            int numberImportedAttendees = 0;
            //Code Added To check file extension
            //string extension = (Path.GetExtension(attendeeFile.FileName)).ToLower();
            //Check if Input file is good
            if (/*extension!="csv" ||*/ attendeeFile == null || attendeeFile.Length == 0)
            {
                ModelState.AddModelError("attendeeFile", "Invalid file");
            }
            else
            {
                try
                {
                    //Safe way to read a file
                    using (Stream fileStream = attendeeFile.OpenReadStream())
                    {  
                        numberImportedAttendees = _attendeeAccessor.ImportFromFile(fileStream);
                    }
                }
                catch (FormatException ex)
                {
                    ModelState.AddModelError("attendeeFile", ex.Message);
                    foreach(ValidationResult validationResult in _attendeeAccessor.ValidationResults)
                    {
                        ModelState.AddModelError(string.Empty, validationResult.ErrorMessage);
                    }
                }
            }

            return View("Index", new AttendeeIndexViewModel()
            {
                Attendees = _attendeeAccessor.Get(),
                NumberImportedAttendees = numberImportedAttendees
            });
        }
        /*
        /// <summary>
        /// Export Button Event handler
        /// </summary>
        /// <param name="attendeeFile">csv file</param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public void Export()
        {
            //FileStream fileStreamPath = new FileStream(@"Data/LetterFormatting.docx", FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                Document document = new Document();
                document.LoadFromFile(@"Data/LetterFormatting.docx", FileFormat.Docx);
                //string[] fieldNames = { "Name", "College", "JobTitle", "Barcode", "Barcode" };
                //string[] fieldValues = { "Abdellah El Bilali", "Algonquin College", "Enterprise Business Platforms", "931854203", "931854203" };

                IList<Attendee> attendees = _attendeeAccessor.Get();
                
                document.MailMerge.Execute(attendees);

                MemoryStream stream = new MemoryStream();
                document.SaveToFile(@"Result.docx", FileFormat.Docx);
                document.Close();
                System.Diagnostics.Process.Start(@"Result.docx");
            
        }
        */
    }
}

Project/PrizeDraw/Views/Attendee/CreateEdit.cshtml
@model PrizeDraw.DataLayer.Model.Attendee

<h4>Attendee</h4>
<hr />
<div class="row">
    <div class="col-md-8 offset-lg-2 text-left">
        <form asp-action="@ViewContext.RouteData.Values["action"]" asp-controller="Attendee">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobilePhone" class="control-label"></label>
                <input asp-for="MobilePhone" class="form-control" />
                <span asp-validation-for="MobilePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address1" class="control-label"></label>
                <input asp-for="Address1" class="form-control" />
                <span asp-validation-for="Address1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address2" class="control-label"></label>
                <input asp-for="Address2" class="form-control" />
                <span asp-validation-for="Address2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Province" class="control-label"></label>
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JobTitle" class="control-label"></label>
                <input asp-for="JobTitle" class="form-control" />
                <span asp-validation-for="JobTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company" class="control-label"></label>
                <input asp-for="Company" class="form-control" />
                <span asp-validation-for="Company" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Project/PrizeDraw/Views/Attendee/Details.cshtml
@model PrizeDraw.DataLayer.Model.Attendee

<h4>Attendee</h4>
<hr />
<div class="row">
    <div class="col-md-8 offset-lg-2 text-left">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Id)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Id)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.FirstName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FirstName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LastName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LastName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.MobilePhone)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.MobilePhone)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address1)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address1)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Address2)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Address2)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.City)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.City)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Province)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Province)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PostalCode)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PostalCode)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.JobTitle)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.JobTitle)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Company)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Company)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.IsCheckedIn)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IsCheckedIn)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CheckedInTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CheckedInTime)
            </dd>
        </dl>
    </div>
    <div>
        @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        <a asp-action="Index">Back to List</a>
    </div>
 </div>

Project/PrizeDraw/Views/Attendee/Index.cshtml
@using PrizeDraw.DataLayer.Model
@model AttendeeIndexViewModel

<div class="row">
    <div class="col-lg-12">
        <h4>Manage Attendees</h4>
        <div class="text-left">
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            @if (Model.NumberImportedAttendees != null)
            {
                <p>Imported @Model.NumberImportedAttendees.Value attendees</p>
            }
        </div>
        <a class="btn btn-primary floatLeft" asp-action="Create" asp-controller="Attendee">Add New</a>
        <a class="btn btn-secondary floatLeft" href="javascript:showImport();">Import</a>
        <!-- <form asp-action="Export" asp-controller="Attendee" method="post" enctype="multipart/form-data">
         <div>
             <input type="submit" value="Export" />
         </div>
        </form>-->
        <br />
        <div id="importAttendees">
            <hr />
            <div class="text-left">
                <form asp-action="Import" asp-controller="Attendee" method="post" enctype="multipart/form-data">
                    <label for="attendeeFile">Upload Attendees (csv):</label>
                    <input type="file" accept=".csv" id="attendeeFile" name="attendeeFile" />
                    <div class="form-group">
                        <input type="submit" value="Submit" class="btn btn-primary" />
                    </div>
                </form>

            </div>
            <hr />
        </div>
        <br />
        <div>
            <table class="table">
                <thead>
                    <tr>
                        @{ Attendee attendeeDummy = null; /* workaround for viewmodels with internal lists */ }
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.FirstName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.LastName)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.Email)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.MobilePhone)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.JobTitle)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.Company)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => attendeeDummy.IsCheckedIn)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Attendees)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MobilePhone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.JobTitle)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Company)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsCheckedIn)
                            </td>
                            <td>

                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Details", "Details", new { id = item.Id })
                                <!--@Html.ActionLink("Delete", "Delete", new { id = item.Id })-->
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
@section scripts {
    <script>
        $(document).ready(function () {
            $('#importAttendees').hide();
        });

        var importToggle = true;
        function showImport() {
            if (importToggle) {
                $('#importAttendees').fadeIn();
            } else {
                $('#importAttendees').fadeOut();
            }

            importToggle = !importToggle;
        }
    </script>
}