Project/PrizeDraw/Models/Vendor/VendorCreateBalllotViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace PrizeDraw.Models
{
    public class VendorCreateBalllotViewModel
    {
        public int TotalAttendees { get; set; }

        public int AttendeesScanned { get; set; }

        [Required]
        public int? AttendeeId { get; set; }

        public string ScannedAttendeeName { get; set; }
    }
}

Project/PrizeDraw/Models/Vendor/VendorCreateEditViewModel.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using PrizeDraw.DataLayer.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace PrizeDraw.Models
{
    public class VendorCreateEditViewModel
    {
        [Required]
        [StringLength(40)]
        public string Name { get; set; }

        public IFormFile Logo { get; set; }

        public static VendorCreateEditViewModel From(Vendor vendor)
        {
            return new VendorCreateEditViewModel
            {
                Name = vendor.Name
            };
        }

        public Vendor ToVendor()
        {
            Vendor vendor = new Vendor();

            vendor.Name = Name;

            if (Logo != null)
            {
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    Logo.CopyTo(memoryStream);

                    vendor.Logo = memoryStream.ToArray();
                }
            }

            return vendor;
        }
    }
}

Project/PrizeDraw/Models/Vendor/VendorIndexViewModel.cs
using PrizeDraw.DataLayer.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PrizeDraw.Models
{
    public class VendorIndexViewModel
    {
        public IList<Vendor> Vendors { get; set; }
    }
}

Project/PrizeDraw/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using PrizeDraw.DataLayer;
using PrizeDraw.DataLayer.Model;
using PrizeDraw.DataLayer.Providers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrizeDraw.DataLayer.DataAccess;
using PrizeDraw.Models;
using PrizeDraw.DataLayer.Model.Identity;
using Microsoft.AspNetCore.Identity;

namespace PrizeDraw.Controllers
{
    public class VendorController : Controller
    {
        private readonly VendorDataAccessor _vendorDataAccessor;
        private readonly PrizeDataAccessor _prizeDataAccessor;
        private readonly AttendeeDataAccessor _attendeeDataAccessor;
        private readonly UserManager<User> _userManager;

        public VendorController(UserManager<User> userManger, PrizeDrawDatabaseContext context)
        {
            _userManager = userManger;
            _vendorDataAccessor = new VendorDataAccessor(context);
            _prizeDataAccessor = new PrizeDataAccessor(context);
            _attendeeDataAccessor = new AttendeeDataAccessor(context);
        }

        [Authorize(Roles="Admin")]
        //
        public IActionResult Index()
        {
            VendorIndexViewModel viewModel = new VendorIndexViewModel()
            {
                Vendors = _vendorDataAccessor.Get()
            };

            return View(viewModel);
        }

        [HttpGet]
        [Authorize(Roles="Admin")]
        public IActionResult Edit(int? id)
        {
            if (id.HasValue)
            {
                return View("CreateEdit", VendorCreateEditViewModel.From(_vendorDataAccessor.Get(id.Value)));
            }
            else
            {
                return BadRequest();
            }
        }

        [HttpPost]
        [Authorize(Roles="Admin")]
        public IActionResult Edit([FromRoute] int? id, VendorCreateEditViewModel vendorModel)
        {
            IActionResult result;

            if (!ModelState.IsValid || !id.HasValue)
            {
                result = RedirectToAction("Create");
            }
            else
            {
                _vendorDataAccessor.UpdateVendor(id.Value, vendorModel.ToVendor());

                result = RedirectToAction("Index");
            }

            return result;
        }

        [HttpGet]
        [Authorize(Roles="Admin")]
        public IActionResult Create()
        {
            return View("CreateEdit", new VendorCreateEditViewModel());
        }

        [HttpPost]
        [Authorize(Roles="Admin")]
        public IActionResult Create(VendorCreateEditViewModel viewModel)
        {
            IActionResult result;

            if (!ModelState.IsValid)
            {
                result = RedirectToAction("Create");
            }
            else
            {
               _vendorDataAccessor.InsertVendor(viewModel.ToVendor());

                result = RedirectToAction("Index");
            }

            return result;
        }

        [HttpGet]
        [Authorize(Roles="Vendor,Admin")]
        public async Task<IActionResult> CreateBallot()
        {
            IActionResult result;

            User currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (!currentUser.VendorId.HasValue)
            {
                return Error("User account does not have vendor associated");
            }
            else
            {
                int vendorId = currentUser.VendorId.Value;
                result = CreateBallotViewAction(vendorId);
            }

            return result;
        }

        [HttpPost]
        [Authorize(Roles = "Vendor,Admin")]
        public async Task<IActionResult> CreateBallot(int attendeeId)
        {
            User currentUser = await _userManager.GetUserAsync(HttpContext.User);
            if (!currentUser.VendorId.HasValue)
            {
                return Error("User account does not have vendor associated");
            }

            int vendorId = currentUser.VendorId.Value;
            string scannedAttendeeName = null;

            if (ModelState.IsValid && _attendeeDataAccessor.AttendeeExists(attendeeId))
            {
                _prizeDataAccessor.CreatePrizeTickets(vendorId, attendeeId);

                Attendee attendee = _attendeeDataAccessor.Get(attendeeId);
                scannedAttendeeName = attendee.FirstName + " " + attendee.LastName;
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Attendee does not exist");
            }

            return CreateBallotViewAction(vendorId, scannedAttendeeName);
        }

        private IActionResult CreateBallotViewAction(int vendorId, string scannedAttendeeName = null)
        {
            VendorCreateBalllotViewModel viewModel = new VendorCreateBalllotViewModel()
            {
                AttendeesScanned = _attendeeDataAccessor.GetNumberOfAttendeesScannedBy(vendorId),
                TotalAttendees = _attendeeDataAccessor.GetNumberOfAttendees(),
                ScannedAttendeeName = scannedAttendeeName
            };

            return View("CreateBallot", viewModel);
        }

        public IActionResult Error(string message)
        {
            return View("Error", new ErrorViewModel { Message = message });
        }
    }
}

Project/PrizeDraw/Views/Vendor/CreateBallot.cshtml
@{
    ViewData["Title"] = "ballot";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model VendorCreateBalllotViewModel

<div id="topMessage">
    <div asp-validation-summary="ModelOnly" class="text-danger h2"></div>
    @if (!string.IsNullOrWhiteSpace(Model.ScannedAttendeeName))
    {
        <p class="h2 text-success">@Model.ScannedAttendeeName Prize Ballots Created</p>
    }
</div>

<div class="row" id="scannerSection">
    <div class="col-lg-12">
        <h1 class="display-3">Scan Attendee</h1>
        <br />
        <p class="h3">Scan attedee's badge barcode to create a prize ballot</p>
        <br />
        <p class="h1">Or</p>
        <div id="ballot">
            <form id="scannerForm" asp-action="CreateBallot" asp-controller="Vendor" method="post">
                <div class="row">
                    <div class="col-lg-10">
                        <input type="text" id="scannerFormId" name="attendeeId" placeholder="Attendee Barcode" />
                    </div>
                    <div class="col-lg-2">
                        <input type="submit" id="scannerFormBtn" value="Submit" class="btn btn-primary" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="offset-2 col-lg-8">
        <h3 class="h1">Stats</h3>
        <table class="table" id="statsTable">
            <tr>
                <th>Scanned Attendees</th>
                <td>@Model.AttendeesScanned</td>
            </tr>
            <tr>
                <th>Total Attendees</th>
                <td>@Model.TotalAttendees</td>
            </tr>
        </table>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
        var scannerInput = "";

        document.addEventListener('keydown', function (event) {
            if (event.keyCode == 13) {
                $('#scannerFormId').val(scannerInput);
                $('#scannerForm').submit();
            } else {
                scannerInput += event.key;
            }
        });

        $(document).ready(function () {
            setTimeout(fadeOutMessage, 5000);
        });

        function fadeOutMessage() {
            $('#topMessage').fadeOut();
        }
    </script>
}

Project/PrizeDraw/Views/Vendor/CreateEdit.cshtml
@using PrizeDraw.DataLayer.Model
@model VendorCreateEditViewModel

<h4>Vendor</h4>
<hr />
<div class="row">
    <div class="col-md-8 offset-lg-2 text-left">
        <form asp-action="@ViewContext.RouteData.Values["action"]" asp-controller="Vendor" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <span asp-validation-for="Name" class="text-danger"></span>
                <input asp-for="Name" class="form-control" placeholder="Vendor Name" aria-label="Vendor Name" />
            </div>
            <div class="form-group">
                <label asp-for="Logo"></label>
                <input asp-for="Logo" type="file" accept="image/*" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Project/PrizeDraw/Views/Vendor/Index.cshtml
@using PrizeDraw.DataLayer.Model
@model VendorIndexViewModel

<div class="row">
    <div class="col-lg-12">
        <h4>Vendors</h4><a class="btn btn-primary floatLeft" asp-action="Create" asp-controller="Vendor"> Add</a>
        <br />
        <hr />
        <div id="vendorsManage" class="text-left">
            <table>
                <thead>
                    <tr>
                        <th>Logo</th>
                        <th>Name</th>
                        <th>Linked Accounts</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Vendor vendor in Model.Vendors)
                    {
                        <tr>
                            <td>
                                @if (vendor.Logo != null)
                                {
                                    <img src="data:image;base64,@System.Convert.ToBase64String(vendor.Logo)" width="100" height="50" />
                                }
                            </td>
                            <td>@vendor.Name</td>
                            <td>
                                <ul>
                                    @foreach (User user in vendor.Users)
                                    {
                                        <li>
                                        @user.UserName
                                        </li>
                                    }
                                </ul>
                            </td>
                            <td><a asp-controller="Vendor" asp-action="Edit" asp-route-id="@vendor.Id">Edit</a></td>
                        </tr>
                    }
                </tbody>
            </table>
            <hr />
        </div>
    </div>
</div>