Project/PrizeDraw/Controllers/CheckInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrizeDraw.DataLayer;
using PrizeDraw.DataLayer.DataAccess;
using PrizeDraw.DataLayer.Model;
using PrizeDraw.Models;

namespace PrizeDraw.Controllers
{
    public class CheckInController : Controller
    {
        private AttendeeDataAccessor _attendeeAccessor;

        public CheckInController(PrizeDrawDatabaseContext prizeDrawDatabaseContext)
        {
            _attendeeAccessor = new AttendeeDataAccessor(prizeDrawDatabaseContext);
        }

        [HttpGet]
        [Authorize(Roles = "Staff,Admin")]
        //GET: CheckIn
        public IActionResult Index()
        {
            return CreateIndexViewResult(string.Empty);
        }

        [HttpPost]
        [Authorize(Roles = "Staff,Admin")]
        //POST: CheckIn/CheckInAttendee
        public IActionResult CheckInAttendee(int attendeeId)
        {
            string checkedInAttendeeName = string.Empty;

            if (ModelState.IsValid && _attendeeAccessor.AttendeeExists(attendeeId))
            {
                if (!_attendeeAccessor.IsAttendeeCheckedIn(attendeeId))
                {
                    Attendee attendee = _attendeeAccessor.CheckInAttendee(attendeeId);
                    checkedInAttendeeName = attendee.FirstName + " " + attendee.LastName;
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Attendee is already checked in");
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Attendee does not exist");
            }

            return CreateIndexViewResult(checkedInAttendeeName);
        }
        /// <summary>
        /// CreateIndexViewResult - show info about checkin
        /// </summary>
        /// <param name="attendeeName">input attendee name</param>
        /// <returns></returns>
        private IActionResult CreateIndexViewResult(string attendeeName)
        {
            CheckInIndexViewModel checkInIndexViewModel = new CheckInIndexViewModel()
            {
                TotalAttendees = _attendeeAccessor.GetNumberOfAttendees(),
                CheckedInAttendees = _attendeeAccessor.GetNumberOfCheckedInAttendees(),
                CheckedInAttendeeName = attendeeName
            };

            return View("Index", checkInIndexViewModel);
        }
    }
}

Project/PrizeDraw/Controllers/DisplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PrizeDraw.DataLayer;
using PrizeDraw.DataLayer.DataAccess;
using PrizeDraw.DataLayer.Model;
using PrizeDraw.Models;

namespace PrizeDraw.Controllers
{
    public class DisplayController : Controller
    {
        private PrizeDataAccessor _prizeDataAccessor;

        public DisplayController(PrizeDrawDatabaseContext context)
        {
            _prizeDataAccessor = new PrizeDataAccessor(context);
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        //GET: Display
        //@see Views/Display/index.cstml
        public IActionResult Index()
        {
            return View(DisplayIndexViewModel.From(_prizeDataAccessor.Get()));
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        //GET: Display
        //Display the information about the prize 
        //@see View/Display/Details/#
        public IActionResult Details(int? id)
        {
            if (!id.HasValue)
            {
                throw new ArgumentNullException(nameof(id));
            }

            IActionResult result = BadRequest();
            Prize prize = null;
        
            try
            {
                prize = _prizeDataAccessor.Get(id.Value);
            }
            catch
            {
                // Failing to retreive a prize should just redirect back to the prize list.
                result = RedirectToAction("Index");
            }

            if (prize != null)
            {
                DisplayWinningTicketsViewModel displayWinningTicketsModel = new DisplayWinningTicketsViewModel
                {
                    PrizeImage = prize.Image,
                    NextPrizeId = _prizeDataAccessor.GetNextPrize(id.Value)?.Id,
                    PrizeName = prize.Name,
                    PrizeId = prize.Id,
                    NumberOfPrizes = prize.NumberAvailable,
                    SponsorLogo = prize.Sponsor?.Logo,
                    SponsorName = prize.Sponsor?.Name,
                    NumberOfBallots = _prizeDataAccessor.GetNumberOfEligibleBallots(id.Value),
                    PrizesAvailable = _prizeDataAccessor.GetNumberPrizesAvailbleToDraw(id.Value),
                    TotalNumberOfUnwonPrizes = _prizeDataAccessor.GetTotalNumberOfAvailablePrizes(),
                    Winners = _prizeDataAccessor.GetPrizeWinners(id.Value)
                };

                result = View(displayWinningTicketsModel);
            }

            return result;
        }
    }
}

Project/PrizeDraw/Views/Shared/_DisplayLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrizeDraw</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container-fluid">
        <partial name="_HeaderPartial" />
        <main role="main">
            <div class="displayContent">
                @RenderBody()
            </div>
        </main>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Project/PrizeDraw/Views/Shared/_HeaderPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using PrizeDraw.Models
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<header id="header" class="row bg-white">
    <div class="col-lg-8">
        <img src="~/img/DC_FULL_COLOUR.svg"/>
    </div>
    <div id="loginHeader" class="col-lg-4">
        @if (SignInManager.IsSignedIn(User))
        {
            <a id="loggedInLink" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage"class="txt-secondary" >Logged in as @UserManager.GetUserName(User)</a>
            <form id="logoutForm" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                <button id="logout" type="submit" class="txt-secondary btn-link">Logout</button>
            </form>
        }
        else
        {
            <a id="login" asp-area="Identity" asp-page="/Account/Login" class="txt-secondary">Login</a>
        }
    </div>
</header>

Project/PrizeDraw/Views/Shared/_Layout.cshtml
<!-- This file is a templaye for all content pages, similar to a master page
    Contain: header, footer, site navigation, site CSS
    
    -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PrizeDraw</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>

    <!-- Import CSS -->
    <link rel="stylesheet" href="~/css/site.css" />
    
    <!-- Import Font -->
    <link href="https://fonts.googleapis.com/css?family=Oswald&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

</head>
<body>
    <div class="container-fluid">
        <!-- Display Header-->
        <partial name="_HeaderPartial" />
        <main role="main">
            <div>
                <!-- Display Site Navigation -->
                <partial name="_SideMenuPartial" />
            </div>
            <div class="content">
                <!-- Display Site Content -->
                @RenderBody()
            </div>
        </main>
    </div>
    <!-- Check the enviroment
        You can modiy it by right click on the project -> Debug -->
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Project/PrizeDraw/Views/Shared/_SideMenuPartial.cshtml
<!-- Manage Site Navigation
    Set authentication on who can access which menu
    -->
<!-- API for sign in-->
@inject SignInManager<User> SignInManager

<div id="mainMenu" class="bg-lightgreen">
    <ul>
            <li id="home"><a asp-controller="Home" asp-action="Index" class="txt-menu" >Home</a></li>
            @if (SignInManager.IsSignedIn(User))
            {
                @if (User.IsInRole("Staff") || User.IsInRole("Admin"))
                {
                    <li id="checkIn"><a asp-controller="CheckIn" asp-action="Index" class="txt-menu">Check In</a></li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li id="display"><a asp-controller="Display" asp-action="Index" class="txt-menu">Display</a></li>
                }
                @if (User.IsInRole("Vendor") || User.IsInRole("Admin"))
                {
                    <li id="vendor"><a asp-controller="Vendor" asp-action="CreateBallot" class="txt-menu">Vendor</a></li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li id="manage"><a asp-controller="Manage" asp-action="Index" class="txt-menu">Manage</a></li>
                }
            }
        </ul>
</div>